<?php return array(
  array (
    'key' => 'field__logo_white__luca_logo',
    'label' => 'White Logo',
    'name' => 'logo_white',
    'type' => 'image',
    'instructions' => 'Optional (white) logo used on front page. PNG only.',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'return_format' => 'array',
    'preview_size' => 'acf_thumbnail',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
  ),
);