<?php return array (
    'key' => 'group__header_hero__luca_foto',
    'title' => 'Header Hero',
    'fields' => array (
      array (
          'key' => 'field__header_hero_show_hero__luca_foto',
          'label' => 'Show large hero section with background?',
          'name' => 'header_show_hero',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'message' => 'Show large hero section with background',
      ),
      array (
          'key' => 'field__header_hero_image__luca_foto',
          'label' => 'Image',
          'name' => 'header_hero_image',
          'type' => 'image',
          'instructions' => '',
          'required' => 1,
          'conditional_logic' =>  array (
            array (
              array (
                'field' => 'field__header_hero_show_hero__luca_foto',
                'operator' => '==',
                'value' => 1,
              ),
            ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => 'jpg',
      ),
      array (
          'key' => 'field__header_hero_title__luca_foto',
          'label' => 'Title',
          'name' => 'header_hero_title',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' =>  array (
            array (
              array (
                'field' => 'field__header_hero_show_hero__luca_foto',
                'operator' => '==',
                'value' => 1,
              ),
            ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
      ),
      array (
          'key' => 'field__header_hero_content__luca_foto',
          'label' => 'Content',
          'name' => 'header_hero_content',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' =>  array (
            array (
              array (
                'field' => 'field__header_hero_show_hero__luca_foto',
                'operator' => '==',
                'value' => 1,
              ),
            ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'default_value' => '',
          'tabs' => 'visual',
          'toolbar' => 'basic',
          'media_upload' => 0,
      ),
      array (
          'key' => 'field__header_hero_text_shadow__luca_foto',
          'label' => 'Text shadow?',
          'name' => 'header_hero_text_shadow',
          'type' => 'true_false',
          'instructions' => 'Use text shadow for title and description?',
          'required' => 0,
          'conditional_logic' =>  array (
            array (
              array (
                'field' => 'field__header_hero_show_hero__luca_foto',
                'operator' => '==',
                'value' => 1,
              ),
            ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'message' => 'Text shadow',
          'default_value' => 0,
      ),
      array (
          'key' => 'field__header_hero_text_color__luca_foto',
          'label' => 'Text color',
          'name' => 'header_hero_text_color',
          'type' => 'color_picker',
          'instructions' => 'Change the text color',
          'required' => 0,
          'conditional_logic' =>  array (
            array (
              array (
                'field' => 'field__header_hero_show_hero__luca_foto',
                'operator' => '==',
                'value' => 1,
              ),
            ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'default_value' => '#FFFFFF',
      ),
      array (
          'key' => 'field__header_btn_text__luca_foto',
          'label' => 'Button text',
          'name' => 'header_hero_btn_text',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' =>  array (
            array (
              array (
                'field' => 'field__header_hero_show_hero__luca_foto',
                'operator' => '==',
                'value' => 1,
              ),
            ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
      ),
      array (
          'key' => 'field__header_hero_btn_url__luca_foto',
          'label' => 'Button URL',
          'name' => 'header_hero_btn_url',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' =>  array (
            array (
              array (
                'field' => 'field__header_hero_show_hero__luca_foto',
                'operator' => '==',
                'value' => 1,
              ),
            ),
          ),
          'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
      ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'landing-page',
            ),
        ),
        array (
          array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'template-front.php',
            ),
        ),
    ),
    'menu_order' => -10,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
);
