<?php return array(
    array (
    'key' => 'field__footer_title__luca_foto',
    'label' => 'Footer title',
    'name' => 'footer_title',
    'type' => 'text',
    'instructions' => 'The title displayed in footer',
    'default_value' => 'Stay Connected',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'allow_null' => 1,
    'allow_multiple' => 0,
  ),
  array (
    'key' => 'field__footer_subtitle__luca_foto',
    'label' => 'Footer subtitle',
    'name' => 'footer_subtitle',
    'type' => 'text',
    'instructions' => 'Subtitle displayed below the title in footer',
    'default_value' => 'Sign up with your email address to receive news and updates',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'allow_null' => 1,
    'allow_multiple' => 0,
  ),
);
